CDAA: Logs Class Reference
Logs Class Reference
Container for Log objects.
#include <Logs.h>
Public Member Functions
Logs ()
Constructs a new Logs object Initializes the list inside the container.
~Logs ()
Destroys the Logs Will destruct the list inside the container.
void add (Log log)
Adds a Log at the end of the list.
int getSize ()
Returns the amount of log in logs.
Log get (int index)
Returns Log at a given index.
std::string getDebugValues (int nbTabulations)
Returns Logs values, suitable for debugging.
Detailed Description
Container for Log objects.
Logs is a container for Log objects.
The point of this class is nothing more than to make manipulating lists of logs more friendlier using add, get, etc... methods. Consider it equivalent to std::list<Log>
Constructor & Destructor Documentation
Logs()
Logs::Logs ()
Constructs a new Logs object Initializes the list inside the container.
~Logs()
Logs::~Logs ()
Destroys the Logs Will destruct the list inside the container.
Member Function Documentation
add()
void Logs::add (Log log)
Adds a Log at the end of the list.
Parameters
log
get()
Log Logs::get (int index)
Returns Log at a given index.
Parameters
index
Returns
Log
References getDebugValues(), and getSize().
getDebugValues()
std::string Logs::getDebugValues (int nbTabulations)
Returns Logs values, suitable for debugging.
Parameters
nbTabulations Number of tabulations needed to show informations. If called outside of getDebugValues function this value should be set to 0. Inside DebugValue this value should be set to nbTabulations+1 for others getDebugsValues()
Returns
std::string
References get(), getSize(), and toString().
getSize()
int Logs::getSize ()
Returns the amount of log in logs.
Returns
int
The documentation for this class was generated from the following files:
Logs.h
src/Logs.cpp