CDAA: InteractionTodos Class Reference
InteractionTodos Class Reference
Container for InteractionTodo objects.
#include <InteractionTodos.h>
Public Member Functions
InteractionTodos ()
Constructs a new InteractionTodos object with an empty list of InteractionTodo objects.
~InteractionTodos ()
Destroys the Interaction Todos:: Interaction Todos object.
std::list< InteractionTodo > * getItList ()
Returns a pointer on the list of InteractionTodos.
void setItList (std::list< InteractionTodo > *)
Sets itList with a pointer on a a list of Interaction Todo.
void addInteraction (Interaction *)
Method adding to the container the list of InteractionTodo objects from a given Interaction.
As in, the set of links between the given Interaction and all its todos.
Friends
std::ostream & operator<< (std::ostream &, InteractionTodos &)
Overloading of the << operator. Redirects the following string in the output stream :
[InteractionTodo]
[InteractionTodo]
. . . . .
[InteractionTodo].
Detailed Description
Container for InteractionTodo objects.
A container class for InteractionTodos. Represents the idea that a Relational Database only has atomic values
It is not a list of pointers because an InteractionTodo has no reason to exist out of this list. Therefore every time there is the need to use an element of this list, a pointer towards it has to be created.
Example
Here is an example of the itList attribute of an InteractionTodos object with the following interaction :
Interaction * i = new Interaction("Please Valentin we really need to finish this school project. @TODO Brew some coffee @TODO Rush the remaining work")
1st element of itList (InteractionTodo type)
attribute I attribute T
i new Todo("Brew some coffee")
2nd element of itList (InteractionTodo type)
attribute I attribute T
i new Todo("Rush the remaining work")
Relational Database point of view
The whole point of this hard work is to be able to easily work with the database. The previous example easily translates into a Relational Database table :
InteractionTodo Relation
Interaction_ID Todo_ID
. . . . . .
548 24
548 25
. . . . . .
Interaction Relation
Interaction_ID Interaction_Content
547 . . .
548 Please Valentin we really need to finish this school project. @TODO Brew some coffee @TODO Rush the remaining work
549 . . .
Todo Relation
Todo_ID Todo_Content
23 . . .
24 Brew some coffee
25 Rush the remaining work
26 . . .
/!\ In those tables, dates are not taken into account!!!
Constructor & Destructor Documentation
InteractionTodos()
InteractionTodos::InteractionTodos ()
Constructs a new InteractionTodos object with an empty list of InteractionTodo objects.
References setItList().
~InteractionTodos()
InteractionTodos::~InteractionTodos ()
Destroys the Interaction Todos:: Interaction Todos object.
Member Function Documentation
addInteraction()
void InteractionTodos::addInteraction (Interaction * interaction)
Method adding to the container the list of InteractionTodo objects from a given Interaction.
As in, the set of links between the given Interaction and all its todos.
Example
Interaction * i new Interaction("The quick brown fox @TODO jumps over @TODO the lazy dog");
addInteraction(i);
Should add two elements to the list :
new InteractionTodo(i,new Todo("jumps over")) and new InteractionTodo(i,new Todo("the lazy dog"))
Parameters
interaction The interaction to retrieve the Todos from.
References Interaction::getContent(), and getItList().
getItList()
std::list< InteractionTodo > * InteractionTodos::getItList ()
Returns a pointer on the list of InteractionTodos.
Returns
std::list<InteractionTodo>*
setItList()
void InteractionTodos::setItList (std::list< InteractionTodo > * itList)
Sets itList with a pointer on a a list of Interaction Todo.
Parameters
itList
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, InteractionTodos & it) friend
Overloading of the << operator. Redirects the following string in the output stream :
[InteractionTodo]
[InteractionTodo]
. . . . .
[InteractionTodo].
Parameters
os The out stream
it The InteractionTodo object to get values from
Returns
std::ostream&
The documentation for this class was generated from the following files:
InteractionTodos.h
src/InteractionTodos.cpp