CDAA: Contact Class Reference
Contact Class Reference
A contact object represents an entity any user can interact with.
#include <Contact.h>
Public Member Functions
Contact (Logs *logs, const std::string &firstName, const std::string &lastName, const std::string &enterprise, const std::string &mail, const std::string &phone, const Photo &photo)
Constructs a new Contact object from all its parameters. Because the Date() constructor allows it, it sets the creation date of the contact to the current date.
void setEnterprise (const std::string &enterprise)
Sets the Company of a contact. Must at least have one character.
void setMail (const std::string &mail)
Sets the email of a contact. Must at least have one character, one @ and one ".".
void setPhone (const std::string &phone)
set phone of a contact. Must at least have one character
void setPhoto (const Photo &photo)
void addInteraction (Interaction *)
std::string getFirstName ()
Return firstname of client.
std::string getLastName ()
Return lastname of client.
std::string getEnterprise ()
Return enterprise of client.
std::string getMail ()
Return mail of client.
std::string getPhone ()
Return the phone number of client.
Photo getPhoto ()
Return Photo which contain path to real image.
Date getDateOfCreation ()
Return Date which represent when the contact was created.
std::list< Interaction * > getInteractions ()
bool operator== (const Contact &toCompare)
Compares Contact objects and determines if they're equals.
Detailed Description
A contact object represents an entity any user can interact with.
A contact represents an entity akin to a person, a group of persons, a service, a company...
It is the main element of the class - Or at least the one that will be iterated onto the most along Interactions.
A contact stores all of its basic informations (names, mail, etc...), a list of interactions.
Constructor & Destructor Documentation
Contact()
Contact::Contact (Logs * logs, const std::string & firstName, const std::string & lastName, const std::string & enterprise, const std::string & mail, const std::string & phone, const Photo & photo)
Constructs a new Contact object from all its parameters. Because the Date() constructor allows it, it sets the creation date of the contact to the current date.
Parameters
logs Contains all actions / logs applied on this contact
firstName
lastName
entreprise
mail
phone
dateOfCreation
photo
interactions The interaction list of the contact.
References Log::ACTION_CREATION_CONTACT, Logs::add(), setEnterprise(), setMail(), setPhone(), and setPhoto().
Member Function Documentation
addInteraction()
void Contact::addInteraction (Interaction * interaction)
Parameters
Interaction *
References getInteractions().
getDateOfCreation()
Date Contact::getDateOfCreation ()
Return Date which represent when the contact was created.
Returns
Date
getEnterprise()
std::string Contact::getEnterprise ()
Return enterprise of client.
Returns
std::string
getFirstName()
std::string Contact::getFirstName ()
Return firstname of client.
Returns
std::string
getInteractions()
std::list< Interaction * > Contact::getInteractions ()
Returns
std::list<Interaction *>
getLastName()
std::string Contact::getLastName ()
Return lastname of client.
Returns
std::string
getMail()
std::string Contact::getMail ()
Return mail of client.
Returns
std::string
getPhone()
std::string Contact::getPhone ()
Return the phone number of client.
Returns
std::string
getPhoto()
Photo Contact::getPhoto ()
Return Photo which contain path to real image.
Returns
Photo
operator==()
bool Contact::operator== (const Contact & toCompare)
Compares Contact objects and determines if they're equals.
Parameters
toCompare
Returns
bool
setEnterprise()
void Contact::setEnterprise (const std::string & enterprise)
Sets the Company of a contact. Must at least have one character.
Exceptions
invalid_argument enterprise length must be higher than 0
Parameters
enterprise
setMail()
void Contact::setMail (const std::string & mail)
Sets the email of a contact. Must at least have one character, one @ and one ".".
Exceptions
invalid_argument enterprise length must be higher than 0 and one @ and one "."
Parameters
mail
References Log::ACTION_EDIT_MAIL, and Logs::add().
setPhone()
void Contact::setPhone (const std::string & phone)
set phone of a contact. Must at least have one character
Exceptions
invalid_argument phone length must be higher than 0
Parameters
lastName
References Log::ACTION_EDIT_PHONE, and Logs::add().
setPhoto()
void Contact::setPhoto (const Photo & photo)
Parameters
photo
References Log::ACTION_EDIT_PHOTO_CONTACT, and Logs::add().
The documentation for this class was generated from the following files:
Contact.h
src/Contact.cpp