CDAA: Todo Class Reference
Todo Class Reference
Represents a task from an interaction for a contact. Linked to Interaction objects using an InteractionTodo object.
#include <Todo.h>
Public Member Functions
Todo (const Date &, const std::string &)
Constructs a new Todo object from both parameters. Does not parse any tags.
Todo (const std::string &)
Construct a new Todo object from its content. PARSES @DATE TAGS.
Looks for the first occurence of @DATE and checks if the following word is a date to the dd/mm/yyyy format with regex.
It then sets the todo date to that.
If it doesn't match the regex, or there are multiple @DATE elements - Doesn't treat dates at all and sets the date to current date.
void setContent (const std::string &)
Sets the content of a todo without parsing any tags.
void setDate (const Date &)
Sets the date using a date object. Must be valid.
std::string getContent ()
Returns the content of a todo as a string.
Date getDate ()
Returns the date of the todo as a Date object.
bool operator== (Todo &toCompare)
Compares Todo objects and determines if they're equals.
Friends
std::ostream & operator<< (std::ostream &, const Todo &)
Overloading of the << operator. Redirects the following string in the output stream : [ TODO : dd/mm/yyyy ] content
Detailed Description
Represents a task from an interaction for a contact. Linked to Interaction objects using an InteractionTodo object.
A todo object conceptually represent a SINGLE task to do, ponctually, in an interaction that can contain as many todos as it needs.
Todos are defined using @TODO tags in an interaction.
Todos dates are defined using @DATE tags in a todo.
If no date is defined, then it is implied to be the current date!
When printing a todo object, we do not need the tags since they are only needed to retrieve them from interaction contents.
Example
Consider the following interaction object :
Interaction{
content = "Please Valentin we really need to finish this school project. @TODO Brew some coffee @TODO Rush the remaining work tomorrow (the @DATE 26/10/2021)"
date = Date(23/10/2021)
}
The todo objects we want to build here are :
Todo{
content = "Brew some coffee"
date = Date(23/10/2021)
}
Todo{
content = " Rush the remaining work tomorrow (the 26/10/2021)"
date = Date(26/10/2021)
}
Errors
There is only one error to manage here : Imputing a wrong date (incorrect format or whatever) - Or imputing two or more dates.
In both case, if there is an error, then the @DATE(S) will simply remain, not be treated, and the todo will be created at the current date
Constructor & Destructor Documentation
Todo() [1/2]
Todo::Todo (const Date & date, const std::string & content)
Constructs a new Todo object from both parameters. Does not parse any tags.
Parameters
date
content
References setContent(), and setDate().
Todo() [2/2]
Todo::Todo (const std::string & content)
Construct a new Todo object from its content. PARSES @DATE TAGS.
Looks for the first occurence of @DATE and checks if the following word is a date to the dd/mm/yyyy format with regex.
It then sets the todo date to that.
If it doesn't match the regex, or there are multiple @DATE elements - Doesn't treat dates at all and sets the date to current date.
Parameters
content A string containing 0 or 1 "@DATE"
References setContent(), and setDate().
Member Function Documentation
getContent()
std::string Todo::getContent ()
Returns the content of a todo as a string.
Returns
std::string
getDate()
Date Todo::getDate ()
Returns the date of the todo as a Date object.
Returns
Date
operator==()
bool Todo::operator== (Todo & toCompare)
Compares Todo objects and determines if they're equals.
Parameters
toCompare
Returns
true
false
References getContent(), and getDate().
setContent()
void Todo::setContent (const std::string & content)
Sets the content of a todo without parsing any tags.
Parameters
content
setDate()
void Todo::setDate (const Date & date)
Sets the date using a date object. Must be valid.
Parameters
date
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Todo & todo) friend
Overloading of the << operator. Redirects the following string in the output stream : [ TODO : dd/mm/yyyy ] content
Parameters
os
todo
Returns
std::ostream&
The documentation for this class was generated from the following files:
Todo.h
Todo.cpp