CDAA: InteractionTodo Class Reference
InteractionTodo Class Reference
An InteractionTodo objects serves the purpose of linking an Interaction object with a Todo object through their pointers.
#include <InteractionTodo.h>
Public Member Functions
InteractionTodo ()
InteractionTodo (Todo *, Interaction *)
Constructs a new InteractionTodo object from pointers toward an Interaction and a Todo as parameters.
void setT (Todo *)
Sets T to a pointer on Todo
A pointer is required here since we want a single object dynamically allocated in memory to represent a todo.
Two todos from two different interactions with the same content are conceptually NOT equals - Therefore we can use their pointer values (adress) to compare them.
void setI (Interaction *)
Sets I to a pointer on Interaction A pointer is required here since we want a single object dynamically allocated in memory to represent a todo.
Two interactions with the same content are conceptually NOT equals - Therefore we can use their pointer values (adress) to compare them.
Todo * getT ()
Returns a pointer on Todo.
Interaction * getI ()
Returns a pointer on Interaction.
bool operator== (InteractionTodo &toCompare)
Compares InteractionTodo object and determines if they're equals.
Friends
std::ostream & operator<< (std::ostream &, const InteractionTodo &)
Overloading of the << operator. Redirects the following string in the output stream :
Interaction :
[Interaction]
Is linked to the following TODO :
[Todo].
Detailed Description
An InteractionTodo objects serves the purpose of linking an Interaction object with a Todo object through their pointers.
An InteractionTodo object has for sole purpose to link a pointer on Todo and a pointer on Interaction.
It conceptually means "Interaction i CONTAINS Todo t"
It is similar to the way a Relational Database works : Attributes are Atomic since we associate a single interaction with a single todo.
Somewhere in the program will be an InteractionTodos object that acts as a list of InteractionTodo (with a few useful methods to manipulate them) to store all the possible links between existing Interaction objects and Todo objects.
Example
Here is an example of an InteractionTodo object with both its attributes :
attribute I attribute T
new Interaction("Huge meeting @TODO call the boss") new Todo("call the boss")
Constructor & Destructor Documentation
InteractionTodo() [1/2]
InteractionTodo::InteractionTodo ()
InteractionTodo() [2/2]
InteractionTodo::InteractionTodo (Todo * t, Interaction * i)
Constructs a new InteractionTodo object from pointers toward an Interaction and a Todo as parameters.
Parameters
t
i
References setI(), and setT().
Member Function Documentation
getI()
Interaction * InteractionTodo::getI ()
Returns a pointer on Interaction.
Returns
Interaction*
getT()
Todo * InteractionTodo::getT ()
Returns a pointer on Todo.
Returns
Todo*
operator==()
bool InteractionTodo::operator== (InteractionTodo & toCompare)
Compares InteractionTodo object and determines if they're equals.
Parameters
toCompare
Returns
true
false
References getI(), and getT().
setI()
void InteractionTodo::setI (Interaction * i)
Sets I to a pointer on Interaction A pointer is required here since we want a single object dynamically allocated in memory to represent a todo.
Two interactions with the same content are conceptually NOT equals - Therefore we can use their pointer values (adress) to compare them.
Parameters
i
setT()
void InteractionTodo::setT (Todo * t)
Sets T to a pointer on Todo
A pointer is required here since we want a single object dynamically allocated in memory to represent a todo.
Two todos from two different interactions with the same content are conceptually NOT equals - Therefore we can use their pointer values (adress) to compare them.
Parameters
t
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const InteractionTodo & it) friend
Overloading of the << operator. Redirects the following string in the output stream :
Interaction :
[Interaction]
Is linked to the following TODO :
[Todo].
Parameters
os The out stream
it The InteractionTodo object to get values from
Returns
std::ostream&
The documentation for this class was generated from the following files:
InteractionTodo.h
InteractionTodo.cpp