CDAA: Interaction Class Reference
Interaction Class Reference
An interaction is a block of text tagged with @TODO and @DATE to indicate tasks and sets the date of said todos.
#include <Interaction.h>
Public Member Functions
Interaction ()
Interaction (const Date &, const std::string &)
Construct a new Interaction object with a date object and a string.
void setContent (const std::string &)
Sets the content of an interaction.
void setDate (const Date &)
Sets the date of an interaction - Day, Month and Year needed.
std::string getContent ()
The content of an interaction - Will always return a string, be it empty or not.
Date getDate ()
The date of an interaction - Conceptually always equals its date of creation.
bool operator== (Interaction &toCompare)
Compares Interaction objects and determines if they're equals.
Friends
std::ostream & operator<< (std::ostream &, const Interaction &)
Overloading of the << operator. Redirects the following string in the output stream : [ dd/mm/yyyy ] content
Detailed Description
An interaction is a block of text tagged with @TODO and @DATE to indicate tasks and sets the date of said todos.
Class for an Interaction specifications. An instance of Interaction will always contain a string (content) and its date of creation (date) through two attributes. The content of an interaction will always be a single string - And the syntax of an Interaction is as follow :
[Interaction comment] [@TODO todo n°1 [@DATE dd/mm/yyyy]] [@TODO todo n°2 [@DATE dd/mm/yyyy]] . . . . . [@TODO todo n°k [@DATE dd/mm/yyyy]]
With bracketed elements being optional
And k between 0 and infinity (please don't do this) /!\ We do NOT treat the content line by line.
Constructor & Destructor Documentation
Interaction() [1/2]
Interaction::Interaction ()
Interaction() [2/2]
Interaction::Interaction (const Date & date, const std::string & content)
Construct a new Interaction object with a date object and a string.
Parameters
date
content
References setContent(), and setDate().
Member Function Documentation
getContent()
std::string Interaction::getContent ()
The content of an interaction - Will always return a string, be it empty or not.
Returns
std::string
getDate()
Date Interaction::getDate ()
The date of an interaction - Conceptually always equals its date of creation.
Returns
Date
operator==()
bool Interaction::operator== (Interaction & toCompare)
Compares Interaction objects and determines if they're equals.
Parameters
toCompare
Returns
bool
References getContent(), and getDate().
setContent()
void Interaction::setContent (const std::string & content)
Sets the content of an interaction.
Parameters
content
setDate()
void Interaction::setDate (const Date & date)
Sets the date of an interaction - Day, Month and Year needed.
Parameters
date
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Interaction & i) friend
Overloading of the << operator. Redirects the following string in the output stream : [ dd/mm/yyyy ] content
Returns
std::ostream&
The documentation for this class was generated from the following files:
Interaction.h
Interaction_.cpp